### ISSUE TITLE
I imported your project to IDEA to report an error, what is the problem?

### ISSUE THREAD

**Issue by Juneor** [georgeherby/flutter-snippets#11]
Error message：
![图片](https://user-images.githubusercontent.com/6530976/104669126-63c8d280-5714-11eb-9cf8-dc4b1cc03f9f.png)

My IDEA version:
![图片](https://user-images.githubusercontent.com/6530976/104670134-40068c00-5716-11eb-9dbf-a590090ff1e0.png)

**Comment by georgeherby** [comment]
You need to create a file called `gradle.properties` in the root of the project. The below is the content of the file, most of which you will not need unless publishing the plugin but can just copy this file in

```
# General
javaVersion=11
javaTargetVersion=11
# IDE Config
ideaVersion=IU-203.5981.155
ideaType=IU
sources=true
isEAP=false
runGenerators=true
#Plugin Settings
dartVersion=203.5981.152
flutterVersion=51.0.4
pluginSinceBuild=202.0
# Release
intellijToken=TOKEN
version=1.2.0
iteration=dev
releaseChannel=dev
```
