### ISSUE TITLE
Please add "subj" shortcut as in AFS

### ISSUE THREAD

**Issue by bDev10** [georgeherby/flutter-snippets#4]
Thank you for your great plugin.
It would be great if you could add a "subj" shortcut like in [Awesome Flutter Snippets](https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets).

**Comment by georgeherby** [comment]
I am working on aligning with Awesome Flutter Snippets. Coming soon™️

**Comment by georgeherby** [comment]
I have just released version 1.0.0-beta-1 that will be available on Beta track for the plugin

**Comment by bDev10** [comment]
Great, thanks.

**Comment by georgeherby** [comment]
Fixed in #5 
The release will be published today so should be live in the next 2 days
Some shortcuts will be renamed so see new readme
