### ISSUE TITLE
not work scfAppBar etc... snippets in Intellij

### ISSUE THREAD

**Issue by DiegoAlessandro** [georgeherby/flutter-snippets#6]
Flutter Snippets version 0.1.9
Intellij IDEA ULTIMATE 2019.3.1

importMat is working...

**Comment by georgeherby** [comment]
Are you saying everything is not working or just that specific template?

**Comment by xalikoutis** [comment]
only the specific template importMat importCup

**Comment by georgeherby** [comment]
Fixed in #5 
The release will be published today so should be live in the next 2 days
Some shortcuts will be renamed so see new readme
