### ISSUE TITLE
[Feature Request] Add custom snippets

### ISSUE THREAD

**Issue by Babwenbiber** [georgeherby/flutter-snippets#8]
I wonder if it was cool to add custom snippets.

Preferable in the IDE itself since the .xml is kind of hard to extend.

I imagine, that I define a abbreviation and enter my code for it once. Then upon entering the abbreviation I get my code every time I want.

**Comment by georgeherby** [comment]
@Babwenbiber if you want to create your own see this link https://www.jetbrains.com/help/idea/creating-and-editing-live-templates.html

However, if you think its a snippet that might be used by many i can look to add it?

**Comment by Babwenbiber** [comment]
Thanks a lot,
I didn't know that this exists :+1: 
So where is the difference between the snippet and the template?
