### ISSUE TITLE
alertDialog shortcut not working on android studio version 4.1.1 snippets v1.0.0-stable-1

### ISSUE THREAD

**Issue by omar-hanafy** [georgeherby/flutter-snippets#9]
I've tried aspectRatio shortcut other multiple shortcuts and they were working perfectly but "alertDialog" one wasn't working I've tried these:
- restart android studio
- uninstall then install the plugin
- restart my MacBook Pro
but it did not help.
<img width="640" alt="Screen Shot 2020-12-02 at 2 00 53 PM" src="https://user-images.githubusercontent.com/48533144/100870513-64304580-34a7-11eb-849a-7f3a7b245a70.png">

**Comment by georgeherby** [comment]
What version of the plugin are you using?

**Comment by georgeherby** [comment]
I just checked and the documentation is wrong! 

for a dialogue, you need `showDialog`
